swagger: '2.0'
info:
  description: >-
    This is the api definition that every runtime for OpenBrisk must implement to be useful. 
    You can find out more about OpenBrisk at [http://openbrisk.org](http://openbrisk.org).
  version: 1.0.0
  title: OpenBrisk Runtime Specification
  contact:
    email: info@openbrisk.org
  license:
    name: MIT
  basePath: /runtime/v1
  schemes:
    - http
  paths:
    '/'
      get:
        summary: Invoke the function without parameters.
        produces:
          - plain/text
          - application/json
        responses:
          '200':
            description: OK
            examples:
              plain/text: Hallo Welt!
              application/json: |-
                {
                  "value": 500
                  "message": "Hallo Welt!"
                }
          '400':
            description: Bad Request
          '500':
            description: Internal Function Error
      post:
        summary: Invoke the function with parameters.
        consumes:
          - application/json
        produces:
          - plain/text
          - application/json
        responses:
          '200':
            description: OK
            examples:
              plain/text: Hallo Welt!
              application/json: |-
                {
                  "value": 500
                  "message": "Hallo Welt!"
                }
          '400':
            description: Bad Request
          '500':
            description: Internal Function Error
externalDocs:
  description: OpenBrisk documentation available on GitHub.
  url: https://github.com/openbrisk/brisk            